@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System(apiGateway, "API Gateway", "API Gateway to proxy the traffic into the internal network")

System_Boundary(mediaSystem, "Inner Network (K8S cluster). Area: Media System") {
    Container(mediaService, "Media Service", "JS/Go/Python", "Service for uploading and providing media files", $tags="webApp")
}

ContainerDb(mediaDatabase, "Blob database", "S3", "Database to store media files")

cloud CDN

Rel(apiGateway, mediaService, "Upload media user request")
Rel(mediaService, mediaDatabase, "Upload media")
Rel_L(CDN, mediaDatabase, "CDN downloads media from S3")
Rel_L(SeeMainC2Diagram, apiGateway, "Request from LB")

@enduml